server:
  port: 53020
  servlet:
    context-path: /uaa

spring:
  application:
    name: uaa-service
  main:
    allow-bean-definition-overriding: true #允许bean的id或名字重复,不然clientDetailsService会重复
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?userUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.dk.security.distributed.uaa.entity
  mapper-locations: com/dk/security/distributed/uaa/mapper/*.xml

logging:
  level:
    root: info

#服务注册
eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #注册的地址
      defaultZone: http://localhost:53022/eureka/