server:
  port: 53021
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localost:3306/user_db?userUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

logging:
  level:
    root: info

#服务注册
eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #注册的地址
      defaultZone: http://localhost:53022/eureka/